[tool.poetry]
name = "pnadcpy"
version = "0.2.0"
description = "Little script to download PNADC's microdata files"
authors = ["Daniel Komesu <danielkomesu@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.3"
pyarrow = "^8.0.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
pylint = "^2.14.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
